[4830][ADD] stock_move_actual_date: renaming from stock_picking_acutal_date to stock_move_actual_date
qrtl/thc-oca pull request #49
Opened 2024-09-25 02:40 UTC by AungKoKoLin1997

[4830](https://www.quartile.co/web#id=4830&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

I haven't delete `stock_picking_actual_date` in this PR to avoid odoo.sh builds failing. After stock_move_actual_date is installed, we can remove `stock_picking_actual_date`.

2024-09-25 02:40 UTC, AungKoKoLin1997 commented
@kanda999 I think we didn't update the translations since last PR. Can you please update the translations?

2024-09-25 04:42 UTC, AungKoKoLin1997 commented
Add new commit https://github.com/qrtl/thc-oca/pull/49/commits/c245dc61a9715fde1910dc1ca59c79a370fa7fef to prevent the tests CI failed because of stock_picking_actual_date is installed after stock_move_actual_date. This commit doesn't need in actual operation when we replace the module.

2024-10-25 07:56 UTC, yostashiro requested changes
@AungKoKoLin1997 Can you please update the code based on the OCA PR (there should be no openupgradelib dependency).

2024-10-25 08:20 UTC, AungKoKoLin1997 commented
Implementation of `stock.scrap` is included in the latest commit.

2024-10-25 13:15 UTC, yostashiro approved these changes

2025-03-31 00:22 UTC, yostashiro commented on stock_move_actual_date/tests/test_stock_move_actual_date.py
> +        self.assertEqual(scrap.move_id.account_move_ids[0].date, date(2024, 9, 10))
@AungKoKoLin1997 I think we should be able to remove the temp adjustment now. Please update all the relevant open PRs.
```suggestion
        self.assertEqual(scrap.move_id.account_move_ids.date, date(2024, 9, 10))
```

2025-03-31 02:00 UTC, AungKoKoLin1997 commented
@yostashiro OCB is still not reflected with odoo latest updates. The latest update was 3 days ago.
I will rerun CI after OCB is reflected with latest odoo code.

2025-04-11 02:46 UTC, yostashiro approved these changes

2025-04-15 04:40 UTC, yostashiro approved these changes

2025-04-24 02:59 UTC, kanda999 approved these changes

2025-04-24 03:02 UTC, merged